spring:
  main:
    show_banner: false
  hadoop:
    fsUri: hdfs://localhost:8020
    resourceManagerHost: localhost
    resourceManagerPort: 8032
    resourceManagerSchedulerAddress: localhost:8030
  redis:
    port: 6379
    host: localhost
#  yarn:
#    hostdiscovery:
#      pointToPoint: false
#      loopback: false
#      preferInterface: ['eth', 'en']
#      matchIpv4: 192.168.0.0/24
#      matchInterface: eth\\d*
#dataflow:
#  yarn:
#    app:
#      streamappmaster:
#        memory: 512m
#        virtualCores: 1
#      streamcontainer:
#        priority: 5
#        memory: 256m
#        virtualCores: 1
#        javaOpts: "-Xms64m -Xmx256m"
#      taskappmaster:
#        memory: 512m
#        virtualCores: 1
#      taskcontainer:
#        priority: 10
#        memory: 256m
#        virtualCores: 1
#        javaOpts: "-Xms64m -Xmx256m"
