logging:
  level:
    org.springframework.yarn: DEBUG
server:
  port: 0
endpoints:
  shutdown:
    enabled: true
spring:
  main:
    show_banner: false
  cloud:
    dataflow:
      yarn:
        version: "@project.version@"
  yarn:
    applicationBaseDir: /dataflow/apps/task/
    appmaster:
      containerCount: 1
      appmasterClass: org.springframework.cloud.dataflow.yarn.taskappmaster.DataFlowTaskAppmaster
      localizer:
        patterns:
          - "spring-cloud-dataflow-yarn-taskcontainer-*.jar"
          - "servers.yml"
      resource:
        priority: ${dataflow.yarn.app.taskcontainer.priority:10}
        memory: ${dataflow.yarn.app.taskcontainer.memory:256m}
        virtualCores: ${dataflow.yarn.app.taskcontainer.virtualCores:1}
      launchcontext:
        options:
          - ${dataflow.yarn.app.taskcontainer.javaOpts:}
        arguments:
          -Dserver.port: 0
          -Dspring.jmx.enabled: false              
          -Dspring.config.location: servers.yml
        locality: false
        archiveFile: spring-cloud-dataflow-yarn-taskcontainer-${spring.cloud.dataflow.yarn.version}.jar
    endpoints:
      containerregister:
        enabled: false
